//! Property enum identities extracted from the EDT serializer model.

/// Unambiguous top-level metadata field types; captions live in Fluent.
pub(super) const PROPERTY_ENUMS: &[(&str, &str)] = &[
    (
        "AuthenticationSeparation",
        "CommonAttributeAuthenticationSeparation",
    ),
    ("AutoUse", "CommonAttributeAutoUse"),
    (
        "BinaryDataBlockStorageUseMode",
        "BinaryDataBlockStorageUseMode",
    ),
    (
        "BinaryDataStorageLocationUse",
        "BinaryDataStorageLocationUse",
    ),
    ("BinaryDataStorageMode", "BinaryDataStorageMode"),
    ("Category", "CommandGroupCategory"),
    (
        "ChoiceDataGetModeOnInputByString",
        "ChoiceDataGetModeOnInputByString",
    ),
    ("ChoiceFoldersAndItems", "FoldersAndItemsUse"),
    ("ChoiceHistoryOnInput", "ChoiceHistoryOnInput"),
    ("ChoiceMode", "ChoiceMode"),
    ("ClientApplicationTheme", "ClientApplicationTheme"),
    (
        "ClientApplicationWindowsOpenVariant",
        "ClientApplicationWindowsOpenVariant",
    ),
    ("CodeAllowedLength", "AllowedLength"),
    ("CompatibilityMode", "CompatibilityMode"),
    (
        "ConfigurationExtensionCompatibilityMode",
        "CompatibilityMode",
    ),
    (
        "ConfigurationExtensionPurpose",
        "ConfigurationExtensionPurpose",
    ),
    (
        "ConfigurationExtensionsSeparation",
        "CommonAttributeExtensionSeparation",
    ),
    ("CreateOnInput", "CreateOnInput"),
    ("DataHistory", "DataHistoryUse"),
    ("DataLockControlMode", "DefaultDataLockControlMode"),
    ("DataSeparation", "CommonAttributeDataSeparation"),
    ("DatabaseTablespacesUseMode", "DatabaseTablespacesUseMode"),
    ("DefaultRunMode", "ClientRunMode"),
    (
        "DependenceOnCalculationTypes",
        "ChartOfCalculationTypesBaseUse",
    ),
    ("EditType", "EditType"),
    ("FillChecking", "FillChecking"),
    ("FormType", "FormType"),
    ("FullTextSearch", "FullTextSearchUsing"),
    (
        "FullTextSearchOnInputByString",
        "FullTextSearchOnInputByString",
    ),
    ("HTTPMethod", "HTTPMethod"),
    ("HierarchyType", "HierarchyType"),
    ("Indexing", "Indexing"),
    (
        "InformationRegisterPeriodicity",
        "InformationRegisterPeriodicity",
    ),
    ("InterfaceCompatibilityMode", "InterfaceCompatibilityMode"),
    (
        "MainClientApplicationWindowInterfaceVariant",
        "MainClientApplicationWindowInterfaceVariant",
    ),
    (
        "MainClientApplicationWindowMode",
        "MainClientApplicationWindowMode",
    ),
    (
        "MessageDirection",
        "IntegrationServiceChannelMessageDirection",
    ),
    ("ModalityUseMode", "ModalityUseMode"),
    ("MoveBoundaryOnPosting", "MoveBoundaryOnPosting"),
    ("NumberAllowedLength", "AllowedLength"),
    ("ObjectAutonumerationMode", "ObjectAutonumerationMode"),
    ("ObjectBelonging", "ObjectBelonging"),
    (
        "OnMainServerUnavalableBehavior",
        "OnMainServerUnavalableBehavior",
    ),
    ("ParameterUseMode", "CommandParameterUseMode"),
    ("Periodicity", "CalculationRegisterPeriodicity"),
    ("Posting", "Posting"),
    ("PredefinedDataUpdate", "PredefinedDataUpdate"),
    ("QuickChoice", "UseQuickChoice"),
    ("RealTimePosting", "RealTimePosting"),
    ("RegisterRecordsDeletion", "RegisterRecordsDeletion"),
    (
        "RegisterRecordsWritingOnPost",
        "RegisterRecordsWritingOnPost",
    ),
    ("RegisterType", "AccumulationRegisterType"),
    ("Representation", "ButtonRepresentation"),
    ("ReturnValuesReuse", "ReturnValuesReuse"),
    ("ReuseSessions", "SessionReuseMode"),
    ("ScriptVariant", "ScriptVariant"),
    (
        "SearchStringModeOnInputByString",
        "SearchStringModeOnInputByString",
    ),
    ("SeparatedDataUse", "CommonAttributeSeparatedDataUse"),
    ("SequenceFilling", "SequenceFilling"),
    ("SubordinationUse", "SubordinationUse"),
    (
        "SynchronousPlatformExtensionAndAddInCallUseMode",
        "SynchronousPlatformExtensionAndAddInCallUseMode",
    ),
    ("TableDataType", "ExternalDataSourceTableDataType"),
    ("TableType", "ExternalDataSourceTableType"),
    ("TaskNumberAutoPrefix", "TaskNumberAutoPrefix"),
    ("TemplateType", "TemplateType"),
    ("TransactionsIsolationLevel", "TransactionsIsolationLevel"),
    ("TransferDirection", "TransferDirection"),
    ("TypeReductionMode", "TypeReductionMode"),
    ("Use", "AttributeUse"),
    ("UseInInterfaceCompatibilityMode", "FormPreferableInterface"),
    ("UsersSeparation", "CommonAttributeUsersSeparation"),
    (
        "Version85InterfaceMigrationMode",
        "Version85InterfaceMigrationMode",
    ),
    ("WriteMode", "RegisterWriteMode"),
];
